---
title: "Chapter 01 - Data Visualization with ggplot2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
```{r}
library(tidyverse)
```

```{r}
mpg <- ggplot2::mpg
```

## Creating a ggplot
```{r}
# Exemplo no livro - p. 5 
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

## A Graphing Template - Exercises (p. 6)

```{r}
#1
ggplot(data = mpg)
```
```{r}
#2 
nrow(mpg)
ncol(mpg)
# 234 linhas e 11 colunas
```

```{r}
# 3 
?mpg
# drv
# f = front-wheel drive, r = rear wheel drive, 4 = 4wd
```

```{r}
# 4
ggplot(data = mpg) +
  geom_point(mapping = aes(x = hwy, y = cyl))
```

```{r}
# 5
ggplot(data = mpg) +
  geom_point(mapping = aes(x = class, y = drv))
```

## Aesthetic Mappings
```{r}
# Exemplo. pg 8

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
# Exemplo pg. 9
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```


```{r}
# Exemplo pg. 9
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```


```{r}
# Exemplo pg. 9
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```



```{r}
# Exemplo pg. 9
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```


## Aesthetic Mappings - Exercises (p. 12)

```{r}
#1
ggplot(data = mpg) + 
  geom_point(
    mapping = aes(x = displ, y= hwy), color = "blue"
  )
```

```{r}
# 2
head(mpg)
# categorical: manufacturer, model, trans, drv, fl, class
# continuous: displ, year, cyk, cty, hwy
```
```{r}
# 3
# ggplot(data = mpg) +
#  geom_point(aes(x = displ, y = year, shape = cty))

#Erro: A continuous variable can not be mapped to shape
```

```{r}
# 4
 ggplot(data = mpg) +
  geom_point(aes(x = class, y = class, shape = class))

```

```{r}
# 5
 ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, stroke = cty))

```



```{r}
# 6
 ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, color = displ < 5))

```

## Facets

```{r}
# Ex. pg. 14
mpg %>% 
  ggplot() +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)
```

```{r}
# Ex. pg. 14
mpg %>% 
  ggplot() +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)
```


## Facets - Exercises (p. 15)
```{r}
# 1

mpg %>% 
  ggplot() +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ cty)
```

```{r}
# 2

mpg %>% 
  ggplot() +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)

mpg %>% 
  ggplot() +
  geom_point(mapping = aes(x = drv, y = cyl)) 
```
